name: PR Preview Deployment

on:
  pull_request:
    branches: [ main ]

jobs:
  deploy-preview:
    runs-on: ubuntu-latest
    if: github.event.pull_request.head.repo.full_name == github.repository
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v3
        
      - name: Create preview environment
        run: |
          echo "🔄 Creating preview environment for PR #${{ github.event.pull_request.number }}"
          # Comandos para criar ambiente de preview
          
      - name: Comment PR
        uses: actions/github-script@v7
        with:
          script: |
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: '🎯 Preview deployed! Visit: https://bulleye-pr-${{ github.event.pull_request.number }}.preview.com'
            })

---